name: .NET

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build-windows:

    runs-on: windows-2019

    steps:
    - name: Checkout
      uses: actions/checkout@v3
      with:
        fetch-depth: 0
       
    - name: Setup NuGet
      uses: NuGet/setup-nuget@v1
      with: 
        nuget-version: '5.x'
        
    - name: Determine Version
      uses: gittools/actions/gitversion/execute@v0.9.7        
     
    - name: Restore NuGet Packages
      run: nuget restore AxaFrance.Extensions.DependencyInjection.sln
    
    - name: Add msbuild to PATH
      uses: microsoft/setup-msbuild@v1.1

    - name: Build
      run: msbuild AxaFrance.Extensions.DependencyInjection.sln /p:Configuration=Release
    
    - name: Tests
      uses: microsoft/vstest-action@v1.0.0
      with:
        searchFolder: ./test/
        runInParallel: true
